name: release

permissions:
    contents: write

on:
    push:
    pull_request:

env:
    GITHUB_TOKEN: ${{ github.token }}
    RUST_BACKTRACE: 1

jobs:
    release:
        name: Release - ${{ matrix.platform.os-name }}
        strategy:
            fail-fast: false
            matrix:
                platform:
                    - os-name: Linux-x86_64
                      runs-on: ubuntu-latest
                      target: x86_64-unknown-linux-musl
                    - os-name: Linux-aarch64
                      runs-on: ubuntu-latest
                      target: aarch64-unknown-linux-musl
                    - os-name: Linux-riscv64
                      runs-on: ubuntu-24.04-riscv
                      target: riscv64gc-unknown-linux-musl
                      use-cross: false

                    - os-name: Windows-x86_64
                      runs-on: windows-latest
                      target: x86_64-pc-windows-msvc
                    - os-name: Windows-aarch64
                      runs-on: windows-latest
                      target: aarch64-pc-windows-msvc

                    - os-name: macOS-x86_64
                      runs-on: macos-latest
                      target: x86_64-apple-darwin
                    - os-name: macOS-aarch64
                      runs-on: macos-latest
                      target: aarch64-apple-darwin
        runs-on: ${{ matrix.platform.runs-on }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build with Cross
              if: matrix.platform.use-cross != false
              uses: houseabsolute/actions-rust-cross@v1
              env:
                  CRATE_NAME: vermouth
              with:
                  working-directory: ./client
                  command: build
                  target: ${{ matrix.platform.target }}
                  args: "--locked --release"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Install Rust toolchain
              if: matrix.platform.use-cross == false
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: ${{ matrix.platform.target }}
                  override: true
                  profile: minimal

            # targetに応じてcargoもしくはcrossを使用してビルド
            - name: Build with Cargo
              if: matrix.platform.use-cross == false
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --locked --release --target ${{ matrix.platform.target }}
            - name: Wait
              shell: bash
              run: sleep $((RANDOM % 20 + 3))
            - name: Release
              id: release-client-1
              uses: houseabsolute/actions-rust-release@v0
              env:
                  CRATE_NAME: vermouth
              with:
                  working-directory: ./client
                  executable-name: vermouth
                  target: ${{ matrix.platform.target }}
                  extra-files: |-
                      linux.sh
                      windows.bat
                      ./.env.example
                      ../README.md
                  _force-release-for-testing: true
                  action-gh-release-parameters: |
                      {
                          "repository": "NaeCqde/vermouth",
                          "token": "${{ secrets.GITHUB_TOKEN }}"
                      }
            - name: Wait
              if: failure()
              shell: bash
              run: sleep $((RANDOM % 20 + 5))
            - name: Release
              if: failure()
              id: release-client-2
              uses: houseabsolute/actions-rust-release@v0
              env:
                  CRATE_NAME: vermouth
              with:
                  working-directory: ./client
                  executable-name: vermouth
                  target: ${{ matrix.platform.target }}
                  extra-files: |-
                      linux.sh
                      windows.bat
                      ./.env.example
                      ../README.md
                  _force-release-for-testing: true
                  action-gh-release-parameters: |
                      {
                          "repository": "NaeCqde/vermouth",
                          "token": "${{ secrets.GITHUB_TOKEN }}"
                      }

            - name: Build
              uses: houseabsolute/actions-rust-cross@v1
              env:
                  CRATE_NAME: vermouth-server
              with:
                  working-directory: ./server
                  command: build
                  target: ${{ matrix.platform.target }}
                  args: "--locked --release"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Wait
              shell: bash
              run: sleep $((RANDOM % 20 + 3))
            - name: Release
              id: release-server-1
              uses: houseabsolute/actions-rust-release@v0
              env:
                  CRATE_NAME: vermouth-server
              with:
                  working-directory: ./server
                  executable-name: vermouth-server
                  target: ${{ matrix.platform.target }}
                  extra-files: |-
                      example.config.json
                      ../README.md
                  _force-release-for-testing: true
                  action-gh-release-parameters: |
                      {
                          "repository": "NaeCqde/vermouth",
                          "token": "${{ secrets.GITHUB_TOKEN }}"
                      }
            - name: Wait
              if: failure()
              shell: bash
              run: sleep $((RANDOM % 20 + 5))
            - name: Release
              if: failure()
              id: release-server-2
              uses: houseabsolute/actions-rust-release@v0
              env:
                  CRATE_NAME: vermouth-server
              with:
                  working-directory: ./server
                  executable-name: vermouth-server
                  target: ${{ matrix.platform.target }}
                  extra-files: |-
                      example.config.json
                      ../README.md
                  _force-release-for-testing: true
                  action-gh-release-parameters: |
                      {
                          "repository": "NaeCqde/vermouth",
                          "token": "${{ secrets.GITHUB_TOKEN }}"
                      }

            - name: Build
              uses: houseabsolute/actions-rust-cross@v1
              env:
                  CRATE_NAME: vermouth-nanokvm
              with:
                  working-directory: ./nanokvm
                  command: build
                  target: ${{ matrix.platform.target }}
                  args: "--locked --release"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Wait
              shell: bash
              run: sleep $((RANDOM % 20 + 3))
            - name: Release
              id: release-nanokvm-1
              uses: houseabsolute/actions-rust-release@v0
              env:
                  CRATE_NAME: vermouth-nanokvm
              with:
                  working-directory: ./nanokvm
                  executable-name: vermouth-nanokvm
                  target: ${{ matrix.platform.target }}
                  extra-files: |-
                      ./.env.example
                      ../README.md
                  _force-release-for-testing: true
                  action-gh-release-parameters: |
                      {
                          "repository": "NaeCqde/vermouth",
                          "token": "${{ secrets.GITHUB_TOKEN }}"
                      }
            - name: Wait
              if: failure()
              shell: bash
              run: sleep $((RANDOM % 20 + 5))
            - name: Release
              if: failure()
              id: release-nanokvm-2
              uses: houseabsolute/actions-rust-release@v0
              env:
                  CRATE_NAME: vermouth-nanokvm
              with:
                  working-directory: ./nanokvm
                  executable-name: vermouth-nanokvm
                  target: ${{ matrix.platform.target }}
                  extra-files: |-
                      ./.env.example
                      ../README.md
                  _force-release-for-testing: true
                  action-gh-release-parameters: |
                      {
                          "repository": "NaeCqde/vermouth",
                          "token": "${{ secrets.GITHUB_TOKEN }}"
                      }
